# Generated by Django 2.2.4 on 2019-08-15 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
