# Generated by Django 2.2.4 on 2019-08-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('avatar', models.CharField(max_length=180, null=True, verbose_name='Аватарка')),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='news.User', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Заголовок'),
        ),
    ]
