# Generated by Django 2.2.4 on 2019-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_new_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Authors',
        ),
        migrations.AddField(
            model_name='new',
            name='author',
            field=models.ForeignKey(default=1, on_delete='SET_NULL', to='news.Authors'),
            preserve_default=False,
        ),
    ]
