# Generated by Django 2.2.4 on 2019-08-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190815_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Имя'),
        ),
    ]
