# Generated by Django 2.2.4 on 2019-08-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190815_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новости'},
        ),
    ]
