# Generated by Django 2.2.4 on 2019-08-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190815_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=80, verbose_name='Тэг')),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='tag',
            field=models.ManyToManyField(to='news.Tag'),
        ),
    ]
