# Generated by Django 2.2.4 on 2019-08-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190820_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='author',
        ),
    ]
