# Generated by Django 2.2.4 on 2019-08-20 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0011_remove_new_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='author',
            field=models.ForeignKey(default=0, on_delete='SET_NULL', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
