# Generated by Django 2.2.4 on 2019-08-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_new_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.ForeignKey(on_delete='SET_NULL', to='news.Authors'),
        ),
    ]
