# Generated by Django 2.2.4 on 2019-08-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_new_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
