# Generated by Django 2.2.4 on 2019-08-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20190820_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='url_avatar',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
