# Generated by Django 2.2.4 on 2019-08-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20190820_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='url_avatar',
            new_name='avatar',
        ),
    ]
