# Generated by Django 2.2.4 on 2019-08-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20190820_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.FileField(upload_to=''),
        ),
    ]
