# Generated by Django 2.2.4 on 2019-08-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20190820_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='picture',
            field=models.FileField(default='pictures/default.jpg', upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.FileField(upload_to='avatars/', verbose_name='Картинка к новости'),
        ),
    ]
